apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-shopping-cart-deployment
  labels:
    app: nodejs-shopping-cart
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nodejs-shopping-cart
  template:
    metadata:
      labels:
        app: nodejs-shopping-cart
    spec:
      containers:
        - name: nodejs-shopping-cart
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
