

replicaCount: 2

image:
  repository: myacrrepo309.azurecr.io/nodejs-shopping-cart1
  tag: latest
  pullPolicy: Always

containerPort: 3000

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: nginx
  host: nodejs-shopping-cart.local
  path: /

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  cpuUtilization: 70
